### ISSUE TITLE
TypeError: Cannot read property 'ownerDocument' of null - when using react-test-renderer

### ISSUE THREAD

**Issue by isilweo** [react-component/slider#338]
Hey,

#326 broke snapshot testing for me. I can mock rc-slider but this would be against reason snapshot tests are for.

this is line, responsible for error. Maybe it would be enought to add null check here.
https://github.com/react-component/slider/pull/326/files#diff-82bbf536b7291bf2c65d9a6effc28a19R90

error below
```javascript
      at ComponentEnhancer.componentDidMount (node_modules/rc-slider/lib/common/createSlider.js:195:39)
      at commitLifeCycles (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:5461:24)
      at commitAllLifeCycles (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6250:9)
      at HTMLUnknownElement.callCallback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2210:14)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:219:27)
      at HTMLUnknownElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:126:9)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:87:17)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/nodes/HTMLElement-impl.js:36:27)
      at HTMLUnknownElement.dispatchEvent (node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:61:35)
      at Object.invokeGuardedCallbackDev (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2249:16)
      at invokeGuardedCallback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2106:29)
      at commitAllWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6371:9)
      at workLoop (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6643:13)
      at HTMLUnknownElement.callCallback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2210:14)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:219:27)
      at HTMLUnknownElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:126:9)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:87:17)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/nodes/HTMLElement-impl.js:36:27)
      at HTMLUnknownElement.dispatchEvent (node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:61:35)
      at Object.invokeGuardedCallbackDev (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2249:16)
      at invokeGuardedCallback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2106:29)
      at performWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6756:7)
      at scheduleUpdateImpl (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7141:19)
      at scheduleUpdate (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7080:12)
      at scheduleTopLevelUpdate (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7351:5)
      at Object.updateContainer (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7381:7)
      at Object.create (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:8186:18)
      at Object.<anonymous> (utils/storiesTestCreator.js:16:50)
          at Promise (<anonymous>)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by polkpolio1** [comment]
Look on this issues:
https://github.com/facebook/react/issues/7740
https://github.com/facebook/react/issues/7371
https://github.com/facebook/react/issues/9244
As I understand it, the best idea is to mock it. The last issue is the same problem with another antd project.

**Comment by paranoidjk** [comment]
@yesmeck Any suggestion about how to test refs with react-test-rerender?

**Comment by yesmeck** [comment]
Issues @polkpolio1 post above explain this issue well, anyway I recommend enzyme + [enzyme-to-json](https://github.com/adriantoine/enzyme-to-json) for React testing, it's [recommended](https://reactjs.org/docs/test-utils.html#overview) on reactjs.org too.

**Comment by paranoidjk** [comment]
Close since we can not help with this problem.

You may see example of rc-slider itself's test setting:
https://github.com/react-component/slider/blob/master/package.json#L48
https://github.com/react-component/slider/tree/master/tests
